In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
weight = .1
def neural_network(input, weight):
    return input * weight
     

In [3]:
number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input,weight)

In [4]:
pred

0.8500000000000001

In [7]:
def w_sum(a, b):
    assert len(a) == len(b)
    return np.sum(np.array(a) * np.array(b))

In [8]:
def neural_network(input, weight):
    return w_sum(input, weight)

In [9]:
weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

In [10]:
pred

0.9800000000000001

In [11]:
weights = [.1, .2, 0]
def neural_network(input, weights):
    return input @ weights

In [12]:
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

In [13]:
pred

0.9800000000000001

In [14]:
def ele_mul(number, vector):
    return [number * vec for vec in vector]

In [15]:
def neural_network(input, weights):
    return ele_mul(input, weights)


In [16]:
wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]

In [17]:
pred = neural_network(input,weights)

In [18]:
pred

[0.065, 0.13, 0.0]

In [19]:
weights = [0.3, 0.2, 0.9]

In [20]:
pred = neural_network(input,weights)

In [21]:
pred

[0.195, 0.13, 0.5850000000000001]

In [22]:
weights = [ [0.1, 0.1, -0.3], # hurt?
[0.1, 0.2, 0.0], # win?
[0.0, 1.3, 0.1] ] # sad?

In [23]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

In [24]:
input = [toes[0],wlrec[0],nfans[0]]

In [33]:
def vec_mat_mul(vector, matrix):
    return vector @ matrix.T
def neural_network(input, weights):
    return vec_mat_mul(np.array(input), np.array(weights))

In [34]:
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0],wlrec[0],nfans[0]]
pred = neural_network(input,weights)

In [35]:
pred

array([0.555, 0.98 , 0.965])

In [29]:
np.array(input)

array([8.5 , 0.65, 1.2 ])

In [30]:
np.array(weights)

array([[ 0.1,  0.1, -0.3],
       [ 0.1,  0.2,  0. ],
       [ 0. ,  1.3,  0.1]])

In [32]:
0.85 + 0.065 - 0.36

0.555

In [38]:
(np.array(input) * np.array(weights)).sum(axis=1)

array([0.555, 0.98 , 0.965])

In [39]:
ih_wgt = [ [0.1, 0.2, -0.1], # hid[0]
[-0.1,0.1, 0.9], # hid[1]
[0.1, 0.4, 0.1] ] # hid[2]
#hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1, -0.3], # hurt?
[0.1, 0.2, 0.0], # win?
[0.0, 1.3, 0.1] ] # sad?

In [40]:
weights = [ih_wgt, hp_wgt]

In [43]:
def neural_network(input, weights):
    input = np.array(input)
    weights = np.array(weights)
    hid = vec_mat_mul(input, weights[0])
    pred = vec_mat_mul(hid, weights[1])
    return pred

In [44]:
neural_network(input, weights)

array([0.2135, 0.145 , 0.5065])

In [45]:
import numpy as np
# toes % win # fans
ih_wgt = np.array([
[0.1, 0.2, -0.1], # hid[0]
[-0.1,0.1, 0.9], # hid[1]
[0.1, 0.4, 0.1]]).T # hid[2]
# hid[0] hid[1] hid[2]
hp_wgt = np.array([
[0.3, 1.1, -0.3], # hurt?
[0.1, 0.2, 0.0], # win?
[0.0, 1.3, 0.1] ]).T # sad?
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)

In [46]:
pred

array([0.2135, 0.145 , 0.5065])